version: '3.7'
services:

  desafio-api:
    build:
      context: .
    container_name: desafio-api
    image: desafio-api:latest
    ports:
      - "8080:8080"
    networks:
      - desafio-network
    restart: unless-stopped

networks:
  desafio-network:
    name: desafio-network